[package]
name = "synth-converter"
version = "0.1.0"
edition = "2021"


[[bin]]
name = "synth-converter"
path = "synth-converter/src/main.rs"

[dependencies]
serde = { version = "1.0.215", features = ["derive"] }
serde_json = "1.0.132"
