[package]
name = "synth-converter"
version = "0.1.0"
edition = "2021"

[dependencies]
jsonschema = "0.22.3"
serde_json = "1.0.128"
#sophia_jsonld = "0.8.0"
sophia = { version = "0.8.0-alpha.3", features = ["jsonld"] }
