[package]
name = "zarr-converter"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.95"
clap = "4.5.24"
ndarray = "0.16.1"
serde_json = "1.0.133"
zarrs = "0.18.3"
zarrs_filesystem = "0.2.0"
