[package]
name = "zarr-converter"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.3.0", features = ["derive"] }
ndarray = "0.16.1"
serde_json = "1.0.133"
zarrs = "0.18.3"
zarrs_filesystem = "0.2.0"
